apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: bot-cleaner
  labels:
    app: bot-cleaner
spec:
  type: NodePort
  ports:
  - port: 80
    name: bot-cleaner
    targetPort: 80
    nodePort: 32756
  selector:
    app: bot-cleaner
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bot-cleaner-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bot-cleaner
    spec:
      containers:
      - name: bot-cleaner
        image: opria123/bot-cleaner:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80